quadrantChart
    title Reach and engagement of CLI games
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    Pac-Man by Namco: [0.8, 0.9]
    Snake by Nokia: [0.7, 0.8]
    CLI Tetris by Alexei Matyushkin: [0.5, 0.7]
    CLI Minesweeper by Keshav Saharia: [0.4, 0.6]
    CLI Chess by Timo Furrer: [0.3, 0.5]
    CLI Sudoku by Michael Hartl: [0.2, 0.4]
    CLI Hangman by Michael Hartl: [0.1, 0.3]
    Our Target Product: [0.6, 0.7]